### ISSUE TITLE
Compliance section missing

### ISSUE THREAD

**Issue by elarguioui** [lacework/extensible-reporting#80]
Hello All, 

In December, Lacework policies and reports have been updated with the latest benchmarks: CIS 1.4 for AWS, CIS 1.5 for Azure, and CIS 1.3 for Google Cloud. 
Since that update the script don't provide the compliance information.

Can you help on that issue?

Thank you in advance.
Best regards, 
Saddik

**Comment by jvogt** [comment]
I believe this is resolved
